# Dependencies
markdown:         kramdown
redcarpet:
 extensions: ["fenced_code_blocks", "autolink", "tables"]

highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            CHS summer seminar 2018
tagline:          'Introduction to the Homer Multitext project'
description:      ''
baseurl: '/chsseminar/'



author:
  name:           'Neel Smith'



links:
  - title: Key links
    url: /links
  - title: Week 1 schedule
    url: /week1
  - title: Travel to CHS
    url: /travel
